### ISSUE TITLE
Segmentation fault for a specific chromosome

### ISSUE THREAD

**Issue by mullerbsf** [vibansal/crisp#20] opened 2020-06-22 15:42 UTC
Dear Vikas Bansal, 

I ran CRISP using --regions by chromosome with the following options:
CRISP --bams ${LIST_OF_BAMS} --ref ${FASTAREF} --regions ${REGIONS} --poolsize 10 --perms 100000 --mmq 10 --minc 3 \
--EM 1 --VCF ${FILE_CODE}_snps_and_indels_pt${SLURM_ARRAY_TASK_ID}.vcf > ${FILE_CODE}_variantcalls_pt${SLURM_ARRAY_TASK_ID}.log

Everything ran normally (chr1-3, and chr5-10), except for one chromosome (chr4) that I am getting the "Segmentation fault" issue.

I found this here https://github.com/vibansal/crisp/issues/16. However, I used the same alignment (bam) and genome files (fa) that I used in BWA, GATK, and CRISP. It is so weird that I ran it in an array and all other chromosomes worked. 

All the time that I tried to rerun it for chr4, I have the same issue in the same position (53323257) in this chromosome:

Chr4    53323257        .       T       C       207     LowMQ10;LowDepth        NP=2;DP=15,12,0;VT=SNV;CT=-inf;VP=1;VF=EMpass;AC=6;AF=0.34092;EMstats=20.76:-11.10;HWEstats=-0.0;MQS=2,9,8,42;FLANKSEQ=gaatacttct:T:cacatgggga  AC:GQ:DP:ADf:ADr:ADb    0:2:25:11,0:9,0:0,0     6:1:36:0,4:0,3:

Could you please help me to identify the possible problem?

Thank you!
Barbara.

**Comment by vibansal** [comment] 2020-06-26 18:32
It is difficult to debug this without having the data, but can you run the code in the region that gives the segfault using a debugger (e.g. gdb) and share the output?

**Comment by mullerbsf** [comment] 2023-12-14 10:21
How do you suggest to run the debugger in a particular position? Can you send a code example?

**Comment by cribe78** [comment] 2024-10-09 16:32
I have identified the cause of the error in identify_indelalleles in parsebam/process_indel_variant.c.   

indelalleles is allocated at line 97:
`struct INDEL* indelalleles = (struct INDEL*)malloc(sizeof(struct INDEL)*10); int alleles =0;` 

The subsequent for loop on line 100 completes without ever satisfying the if conditions on lines 102 and 103.  No values are assigned to the indelalleles array.

There SEGFAULT occurs at line 158 when indelalleles[0].bases is accessed:
`varalleles =1; strcpy(variant->itb[4],indelalleles[0].bases); `

**Comment by vibansal** [comment] 2024-10-09 19:36
Many thanks for finding the source for the segfault. I have updated the code to fix it. Greatly appreciated!

**Comment by cribe78** [comment] 2024-10-11 16:27
Thank you for implementing the fix so quickly!  I have tested it on Barbara's data as originally reported in this issue and it works now.

**Comment by vibansal** [comment] 2024-10-11 16:38
Excellent, I will close this issue for now.

**Closed by vibansal** 2024-10-11 16:38 UTC
